### PR TITLE
Fix TypeError by initializing keepRoundedCorners with default values

### LINKED ISSUE #52: After updating the plug-in, the plug-in does not work
I am gnome46 desktop. When I restarted my computer, the plugin prompted me that the plugin had been updated, so I logged out. After logging out, the plugin doesn't work.

Here is the error log: Extension rounded-window-corners
The extension rounded-window-corners@fxgn was set incorrectly:
``
TypeError: this._cfg.keepRoundedCorners is undefined

Stack tracking:
  @file:///home/wuxuming/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/preferences/pages/general.js:57:9
  pages@file:///home/wuxuming/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/preferences/index.js:5:5
  fillPreferencesWindow@file:///home/wuxuming/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/preferences.js:23:28
  _loadPrefs@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:41:18
  async* _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:26:14
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:17:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:139:33
  async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
  _wrapJSObject/<<@resource://g/gnome/gjs/modules/core/overrides/Gio.js:408:34
  _init/GLib.MainLoop.prototype.runAsync/</<@resource://g/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
``

图片

### PR DESCRIPTION
**Pull request by satrujit11**
### Overview
This PR fixes a `TypeError` that occurred when accessing the `keepRoundedCorners` property of the configuration object (`this._cfg`) in the `rounded-window-corners` extension. The error was due to `keepRoundedCorners` being undefined.

### Changes Made
- Added a check to ensure `this._cfg.keepRoundedCorners` is properly initialized.
- Default values are set for `keepRoundedCorners.maximized` and `keepRoundedCorners.fullscreen` properties to prevent runtime errors.
- This change ensures the extension's settings page loads without errors and improves stability.

### Testing
- Tested the changes by opening the preferences window and toggling the settings. No errors were encountered.

### Additional Context
This change is necessary to avoid crashes when the preferences window is accessed, especially in cases where the `keepRoundedCorners` settings have not been initialized by the user or are missing in the configuration file.

Please review the changes and provide feedback. Thank you!

Closes #52 #50

### CODE REVIEW

**Comment by flexagoon** [comment]
This is not what the issue is. You can't just initialize the variable with a default value, since you'll still have invalid dconf settings.

**Comment by satrujit11** [comment]
Then, after providing the variable with a default value, we can save the defaults back to dconf. This way, we will not have invalid dconf settings.

> **NOTE :** I am a web developer & certainly a beginner in Gnome development, so please forgive me if I say anything foolish. I am just researching and trying to learn the Gnome way while fixing this bug. 
Thank You

**Comment by flexagoon** [comment]
Sorry if my initial response sounded a little harsh, I literally just woke up and the first thing I see is a bunch of emails about my extension being broken and I had to rush to my computer to fix it, so I was a bit panicked and annoyed

> I am just researching and trying to learn the Gnome way while fixing this bug.

No problem, I literally didn't know anything about gnome development or even typescript before I started maintaining this. I can explain what the issue was if you want:

---

All extension settings are defined in a [schema file](https://github.com/flexagoon/rounded-window-corners/blob/main/resources/schemas/org.gnome.shell.extensions.rounded-window-corners-reborn.gschema.xml), which lists all of the setting names, types and default values. However, if the schema changes, you'll still have old preferences left around that don't fit in the new schema, so you may have an error.

To fix this, we need to store a version of the setting schema, and if the version the user has is lower than the latest version, we remove all outdated settings. This is handled by [this function here](https://github.com/flexagoon/rounded-window-corners/blob/7723e538274426bcc5131e077c0b95d208dceea1/src/utils/settings.ts#L118-L140).

As you can see, there's a `lastVersion` variable there, which the current version is checked against. It's currently set to 6. The issue was that it was previously set to 5, however the old schema also had the version code of 5, so the function saw that the version code matches, decided that the user has the latest schema version and didn't reset any settings. This means the user had old settings, which used a `keep_rounded_corners` key instead of `keepRoundedCorners`, so when the extension tried to access the new key it was null and threw an error.

**Comment by satrujit11** [comment]
Thank you for the response. Now I somewhat understand the problem.

I really appreciate it!

**Pull request closed without merging**
